name = "trainb0y's 1.19 Visual Pack"
author = "trainb0y"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5eaf4e1acd91714c8271e176cfcbfb2a062a699a43c97ce8153855772417ac83"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
